#include <iostream>
#include <vector>
#include <thread>
#include <vector>
#include <string>
#include <sstream>
#include <cmath>
#include <regex>
#include <cstdlib> // Required for atof

// brew install nlohmann-json
// sudo apt install nlohmann-json3-dev
#include <nlohmann/json.hpp>

// brew install zeromq cppzmq
#include <zmq.hpp>

#include "WheelWrapper.hpp"
#include "Logger.hpp"
#include "Configs.hpp"

/*
==============================================================================
ZMQUpdater
==============================================================================

Purpose:
- Bridge between external ZMQ traffic and internal shared data structures.
- Inbound path: read JSON messages and update matching Sensor objects.
- Outbound path: publish wheel setpoint commands generated by wheel loops.

Runtime model:
- Designed to run in its own thread.
- Uses non-blocking receives to drain all currently queued inbound messages.
- Publishes setpoints continuously in the run loop.

Message expectations:
- Inbound: JSON containing at least subject_id and type.
- Outbound: JSON encoded in the suspension setpoint format expected by the
  downstream consumer.
*/
class ZMQUpdater {
private:
    // Shared data containers used by all control threads.
    ZMQSensorData& sensors;
    ZMQOutput&     output;

    // Shared logger for initialization and fatal-error status.
    Logger& logger;

    // Verbose mode toggle for high-frequency debug output.
    // When true, inbound key/value parsing details are printed to stdout.
    bool verbose;

    // ZMQ communication objects.
    zmq::context_t zmq_context;
    zmq::socket_t  socket_in;
    zmq::socket_t  socket_out;

public:
    // Constructor
    // - zmq_in: endpoint this wrapper subscribes to for sensor updates
    // - zmq_out: endpoint this wrapper publishes setpoint outputs to
    // - verbose_mode: enables/disables detailed stdout debug logging
    ZMQUpdater(std::string zmq_in, std::string zmq_out, ZMQSensorData& sensors_object, ZMQOutput& output_object, Logger& logger_object, bool verbose_mode = false) 
        : sensors(sensors_object), output(output_object), logger(logger_object), verbose(verbose_mode) {

        // Initialize context with one IO thread.
        zmq_context = zmq::context_t(1);
            
        // Inbound SUB socket setup.
        socket_in = zmq::socket_t(zmq_context, zmq::socket_type::sub);

        // Subscribe to all topics/messages on this endpoint.
        socket_in.set(zmq::sockopt::subscribe, "");
        socket_in.connect(zmq_in);

        // Outbound PUB socket setup.
        socket_out = zmq::socket_t(zmq_context, zmq::socket_type::pub);
        socket_out.connect(zmq_out);

        // Emit startup summary to confirm endpoint wiring.
        logger.log("ZMQUpdater", "ZMQUpdater initialized. Subscribed to: " + zmq_in + ", publishing to: " + zmq_out);
    }

    // Update verbose mode at runtime.
    void setVerbose(bool verbose_mode) {
        verbose = verbose_mode;
    }

    // Read current verbose state.
    bool isVerbose() const {
        return verbose;
    }

    // Drain all currently unread inbound messages without blocking.
    // Returns a vector of raw JSON strings.
    std::vector<std::string> getAllUnreadZMQMessages(zmq::socket_t& subSocket) {
        std::vector<std::string> messages;
        zmq::message_t msg;

        // Keep receiving until queue is empty.
        while (subSocket.recv(msg, zmq::recv_flags::dontwait)) {
            messages.push_back(msg.to_string());
        }
        return messages;
    }

    // Parse inbound JSON and update matching Sensor objects.
    void updateSensorsFromZMQ() {
        // Example payloads:
        // {"subject_id": 578, "type":"uavcan.primitive.String_1_0", "value": "sup dood"}
        // {"subject_id": 908, "type":"cwrubaja.suspension.vcm.Setpoint_0_2", "priority": 2, "current": {"ampere": 0.4}}
        // {"timestamp": {"microsecond": 0}, "radian_per_second": 2.501599205562144e-10, "subject_id": 1000}
        // {"latitude_degrees": 0.0, "longitude_degrees": 0.0, "altitude": {"meter": 0.0}, "subject_id": 480}


        // Read every queued message this cycle.
        auto messages = getAllUnreadZMQMessages(socket_in);
        if (messages.empty()) return;

        // Parse and map each message into internal sensor storage.
        for (const auto& msg : messages) {
            try {
                // Decode JSON text.
                auto json = nlohmann::json::parse(std::string(msg));

                // Identify which sensor object should be updated.
                int subject_id = json["subject_id"];

                // Throws if subject_id is unknown.
                Sensor& curret_sensor = sensors.getAt(subject_id);

                // Copy all relevant top-level fields into Sensor::data_map.
                for (auto& [key, value] : json.items()) {

                    // Verbose print of every key-value pair for development/debugging.
                    if (verbose) {
                        std::cout << key << " : " << value << std::endl;
                    }

                    // Metadata fields are used for routing/schema, not data payload.
                    if (key == "subject_id" || key == "type") {
                        continue;
                    } else {

                        // Parsed/stored representation for Sensor::data_map.
                        std::any assgin_data;

                        // Extract numeric tokens directly so exponent notation like
                        // 2.501599205562144e-10 is preserved and JSON key names are ignored.
                        std::string values_str = value.dump();
                        static const std::regex number_pattern(R"([-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?)");

                        std::vector<double> values_vector;
                        for (std::sregex_iterator it(values_str.begin(), values_str.end(), number_pattern), end; it != end; ++it) {
                            values_vector.push_back(std::stod(it->str()));
                        }

                        if (values_vector.empty()) {
                            // If no numeric content is found, default to 0.0.
                            assgin_data = 0.0;

                        } else if (values_vector.size() == 1) {
                            // Single value -> store as scalar double.
                            assgin_data = values_vector.front();

                        } else {
                            // Comma-separated values -> store as vector<double>.
                            assgin_data = values_vector;
                        }

                        // Save parsed data under the original key name.
                        curret_sensor.data_map[key] = assgin_data;
                    };
                };
            } catch (const std::exception& e) {
                // Ignore malformed JSON and unknown subject IDs.
                // Keep loop alive for subsequent good messages.
                if (verbose) {
                    std::cout << e.what() << std::endl;
                }
                continue;
            }
        }
    }

    
    // Serialize and publish the four wheel setpoints.
    void publishOutputToZMQ() {

        // Required downstream payload shape:
        // '{"priority": 2, "type":"cwrubaja.suspension.vcm.Setpoint.0.2", "current": {"ampere": 67.0}, "subject_id": 127}'

        // Format helper for one wheel setpoint packet.
        auto format = [](int sub_id, double setpoint) {
            return "{\"priority\": 2, \"type\":\"" + CONFIG_SETPOINT_TYPE + "\", \"current\": {\"ampere\": " + std::to_string(setpoint) + "}, \"subject_id\": " + std::to_string(sub_id) + "}";
        };

        // Publish one packet per wheel each cycle.
        socket_out.send(zmq::message_t(format(CONFIG_FL_SUBJECT_ID, output.FL_setpoint)), zmq::send_flags::dontwait);
        socket_out.send(zmq::message_t(format(CONFIG_FR_SUBJECT_ID, output.FR_setpoint)), zmq::send_flags::dontwait);
        socket_out.send(zmq::message_t(format(CONFIG_BL_SUBJECT_ID, output.BL_setpoint)), zmq::send_flags::dontwait);
        socket_out.send(zmq::message_t(format(CONFIG_BR_SUBJECT_ID, output.BR_setpoint)), zmq::send_flags::dontwait);
    }


    // Main updater loop.
    // Continuously ingests sensor traffic and publishes control outputs.
    void run() {
        try {
            while (true) {
                updateSensorsFromZMQ();
                publishOutputToZMQ();

                // sleep to reduce CPU spin
                usleep(10);
            }

        // Any unhandled exception is treated as fatal for this updater thread.
        } catch (const std::exception& e) {
            logger.log("ZMQUpdater", "ZMQUpdater encountered a fatal error: " + std::string(e.what()));
            throw std::runtime_error("ZMQUpdater encountered a fatal error.");
        }
    }
};
